### PR TITLE
balance testing

### LINKED ISSUE #121: accountBalance + accountBalances
## accountBalance

```js
accountBalance(entropy, address) =>

number
```

## accountBalances

```js
accountBalances(entropy, [addressA, addressB]) =>
{
  addressA: {
    balance: number,
    error: null
  },
  addressB: {
    balance: null,
    error: Error
  }
}
```

NOTE: if one balance fails.... 

if they all error then throw an error

### PR DESCRIPTION
**Pull request by mixmix**
WIP

Depends on : https://github.com/entropyxyz/sdk/pull/389

closes #121

### CODE REVIEW

**Comment by mixmix** [comment]
@rh0delta if you `yarn link` in that associated SDK PR ... then try to run the tests you will see:
```output
yarn run v1.22.1
$ yarn test:types && yarn test:ts && yarn test:only
$ tsc --project tsconfig.json
tests/balance.test.ts:4:21 - error TS2307: Cannot find module '@entropyxyz/sdk/keys' or its corresponding type declarations.

4 import Keyring from '@entropyxyz/sdk/keys'
                      ~~~~~~~~~~~~~~~~~~~~~~

tests/testing-utils/index.ts:1:49 - error TS2307: Cannot find module '@entropyxyz/sdk/dev/testing-utils.mjs' or its corresponding type declarations.

1 import { spinNetworkUp, spinNetworkDown, } from "@entropyxyz/sdk/dev/testing-utils.mjs"
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


```


I think the problem is our `moduleResoltion` in `tsconfig` .... like it's set to some old value `node` when it should be something newer? I dunno, it's a nightmare
https://stackoverflow.com/questions/70296652/how-can-i-use-exports-in-package-json-for-nested-submodules-and-typescript

**Comment by rh0delta** [comment]
> @rh0delta if you `yarn link` in that associated SDK PR ... then try to run the tests you will see:
> 
> ```
> yarn run v1.22.1
> $ yarn test:types && yarn test:ts && yarn test:only
> $ tsc --project tsconfig.json
> tests/balance.test.ts:4:21 - error TS2307: Cannot find module '@entropyxyz/sdk/keys' or its corresponding type declarations.
> 
> 4 import Keyring from '@entropyxyz/sdk/keys'
>                       ~~~~~~~~~~~~~~~~~~~~~~
> 
> tests/testing-utils/index.ts:1:49 - error TS2307: Cannot find module '@entropyxyz/sdk/dev/testing-utils.mjs' or its corresponding type declarations.
> 
> 1 import { spinNetworkUp, spinNetworkDown, } from "@entropyxyz/sdk/dev/testing-utils.mjs"
>                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> I think the problem is our `moduleResoltion` in `tsconfig` .... like it's set to some old value `node` when it should be something newer? I dunno, it's a nightmare https://stackoverflow.com/questions/70296652/how-can-i-use-exports-in-package-json-for-nested-submodules-and-typescript

this has been fixed with edits made in the connected PR on the sdk repo https://github.com/entropyxyz/sdk/pull/389

File: src/common/initializeEntropy.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ const keyrings = {
 export function getKeyring (address) {
   if (!address && keyrings.default) return keyrings.default
   if (address && keyrings[address]) return keyrings[address]
-  return keyrings.default
+  return undefined
```
Comment (frankiebee) [inline src/common/initializeEntropy.ts:23]:
```suggestion
// explicitly return undefined so their is no confusion around what is selcted
  return undefined
```

File: src/common/initializeEntropy.ts [hunk 2]
```diff
@@ -38,7 +38,7 @@ export const initializeEntropy = async ({ keyMaterial, password, endpoint }: Ini
     await wasmGlobalsReady()
 
     const { accountData, password: successfulPassword } = await getAccountDataAndPassword(keyMaterial, password)
-    if (!accountData.seed || !accountData.admin) {
+    if (!accountData.seed && !accountData.admin) {
```
Comment (frankiebee) [inline src/common/initializeEntropy.ts:41]:
```suggestion
// check if their is no admin account and no seed so that we can throw an error
    if (!accountData.seed && !accountData.admin) {
```

File: src/common/initializeEntropy.ts [hunk 3]
```diff
@@ -63,7 +63,7 @@ export const initializeEntropy = async ({ keyMaterial, password, endpoint }: Ini
     }
 
     let selectedAccount
-    const storedKeyring = getKeyring(accountData.admin.address)
+    const storedKeyring = getKeyring(accountData?.admin?.address)
```
Comment (frankiebee) [inline src/common/initializeEntropy.ts:66]: (non blocker) why? 😢

Comment (frankiebee) [reply src/common/initializeEntropy.ts:66]: because admin might not exist

**Review by frankiebee — CHANGES_REQUESTED** [review]
just commit my suggestions they docs @rh0delta
